FROM ruby:3
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt -y upgrade && apt install libjemalloc2 && apt clean
RUN adduser --system --home /blinky --group --uid 800 --disabled-password blinky
RUN gem install bundler
RUN apt -y install gsfonts && apt clean
COPY Gemfile* runapp /blinky/
RUN cd /blinky && bundle --without=shot
COPY bin    /blinky/bin
COPY lib    /blinky/lib
COPY views  /blinky/views
COPY public /blinky/public
EXPOSE 4567
ENV RACK_ENV deployment
ENV APP_CMD exec bundle exec ruby -Ilib bin/frontend.rb -o 0
ENV LD_PRELOAD libjemalloc.so.2
CMD /blinky/runapp
