FROM ruby:2.3
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get -y upgrade; apt-get clean
RUN apt-get -y install gsfonts; apt-get clean
RUN adduser --system --home /blinky --group --uid 800 --disabled-password blinky
ADD ./ /blinky
RUN cd /blinky && bundle --without="web shot"
ENV APP_CMD exec bundle exec ruby -Ilib bin/flush.rb
CMD /blinky/runapp
