FROM ruby:2.4
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade && apt-get clean
RUN adduser --system --home /blinky --group --uid 800 --disabled-password blinky
COPY Gemfile* runapp /blinky/
COPY bin    /blinky/bin
COPY lib    /blinky/lib
COPY views  /blinky/views
COPY public /blinky/public
RUN apt-get -y install gsfonts && apt-get clean
RUN cd /blinky && bundle --without=shot
EXPOSE 4567
ENV RACK_ENV deployment
ENV APP_CMD exec bundle exec ruby -Ilib bin/frontend.rb -o 0
CMD /blinky/runapp
