#!/bin/bash
: ${APP_HOME_DIR:=/blinky}
: ${APP_UID:=800}
: ${APP_GID:=800}
: ${APP_CMD:=exec bundle exec ruby -Ilib frontend.rb -o 0}

if [ "$(id -g blinky)" -ne "${APP_GID}" ]; then
  groupmod --non-unique --gid "${APP_GID}" blinky
fi
if [ "$(id -u blinky)" -ne "${APP_UID}" ]; then
  usermod --non-unique --uid "${APP_UID}" blinky
fi

chown -h blinky:blinky /blinky
chown -fR blinky:blinky /blinky/.cache # for fontconfig cache

cd "${APP_HOME_DIR}"
export HOME="${APP_HOME_DIR}"
export LANG="C.UTF-8"
exec su -p -s /bin/bash -c "${APP_CMD}" blinky
